/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiseasesRouteImport } from './routes/diseases'
import { Route as CareRouteImport } from './routes/care'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as MyOrdersIndexRouteImport } from './routes/my-orders.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ThanhToanOrderIdRouteImport } from './routes/thanh-toan.$orderId'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrderProductIdRouteImport } from './routes/order.$productId'
import { Route as MyOrdersIdRouteImport } from './routes/my-orders.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDiseasesRouteImport } from './routes/admin.diseases'
import { Route as AdminChatbotSettingsRouteImport } from './routes/admin.chatbot-settings'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCareRouteImport } from './routes/admin.care'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesRoute = DiseasesRouteImport.update({
  id: '/diseases',
  path: '/diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIndexRoute = MyOrdersIndexRouteImport.update({
  id: '/my-orders/',
  path: '/my-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanOrderIdRoute = ThanhToanOrderIdRouteImport.update({
  id: '/thanh-toan/$orderId',
  path: '/thanh-toan/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderProductIdRoute = OrderProductIdRouteImport.update({
  id: '/order/$productId',
  path: '/order/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersIdRoute = MyOrdersIdRouteImport.update({
  id: '/my-orders/$id',
  path: '/my-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiseasesRoute = AdminDiseasesRouteImport.update({
  id: '/admin/diseases',
  path: '/admin/diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatbotSettingsRoute = AdminChatbotSettingsRouteImport.update({
  id: '/admin/chatbot-settings',
  path: '/admin/chatbot-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCareRoute = AdminCareRouteImport.update({
  id: '/admin/care',
  path: '/admin/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/admin/products/$id',
  path: '/admin/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot-settings': typeof AdminChatbotSettingsRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/thanh-toan/$orderId': typeof ThanhToanOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot-settings': typeof AdminChatbotSettingsRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/thanh-toan/$orderId': typeof ThanhToanOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/chatbot-settings': typeof AdminChatbotSettingsRoute
  '/admin/diseases': typeof AdminDiseasesRoute
  '/admin/users': typeof AdminUsersRoute
  '/my-orders/$id': typeof MyOrdersIdRoute
  '/order/$productId': typeof OrderProductIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/thanh-toan/$orderId': typeof ThanhToanOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/care'
    | '/admin/categories'
    | '/admin/chatbot-settings'
    | '/admin/diseases'
    | '/admin/users'
    | '/my-orders/$id'
    | '/order/$productId'
    | '/products/$id'
    | '/thanh-toan/$orderId'
    | '/admin/'
    | '/my-orders/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/care'
    | '/admin/categories'
    | '/admin/chatbot-settings'
    | '/admin/diseases'
    | '/admin/users'
    | '/my-orders/$id'
    | '/order/$productId'
    | '/products/$id'
    | '/thanh-toan/$orderId'
    | '/admin'
    | '/my-orders'
    | '/products'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/care'
    | '/admin/categories'
    | '/admin/chatbot-settings'
    | '/admin/diseases'
    | '/admin/users'
    | '/my-orders/$id'
    | '/order/$productId'
    | '/products/$id'
    | '/thanh-toan/$orderId'
    | '/admin/'
    | '/my-orders/'
    | '/products/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  DiseasesRoute: typeof DiseasesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminCareRoute: typeof AdminCareRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminChatbotSettingsRoute: typeof AdminChatbotSettingsRoute
  AdminDiseasesRoute: typeof AdminDiseasesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MyOrdersIdRoute: typeof MyOrdersIdRoute
  OrderProductIdRoute: typeof OrderProductIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ThanhToanOrderIdRoute: typeof ThanhToanOrderIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MyOrdersIndexRoute: typeof MyOrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases': {
      id: '/diseases'
      path: '/diseases'
      fullPath: '/diseases'
      preLoaderRoute: typeof DiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/': {
      id: '/my-orders/'
      path: '/my-orders'
      fullPath: '/my-orders/'
      preLoaderRoute: typeof MyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan/$orderId': {
      id: '/thanh-toan/$orderId'
      path: '/thanh-toan/$orderId'
      fullPath: '/thanh-toan/$orderId'
      preLoaderRoute: typeof ThanhToanOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$productId': {
      id: '/order/$productId'
      path: '/order/$productId'
      fullPath: '/order/$productId'
      preLoaderRoute: typeof OrderProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders/$id': {
      id: '/my-orders/$id'
      path: '/my-orders/$id'
      fullPath: '/my-orders/$id'
      preLoaderRoute: typeof MyOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diseases': {
      id: '/admin/diseases'
      path: '/admin/diseases'
      fullPath: '/admin/diseases'
      preLoaderRoute: typeof AdminDiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chatbot-settings': {
      id: '/admin/chatbot-settings'
      path: '/admin/chatbot-settings'
      fullPath: '/admin/chatbot-settings'
      preLoaderRoute: typeof AdminChatbotSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/care': {
      id: '/admin/care'
      path: '/admin/care'
      fullPath: '/admin/care'
      preLoaderRoute: typeof AdminCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/admin/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  DiseasesRoute: DiseasesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminCareRoute: AdminCareRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminChatbotSettingsRoute: AdminChatbotSettingsRoute,
  AdminDiseasesRoute: AdminDiseasesRoute,
  AdminUsersRoute: AdminUsersRoute,
  MyOrdersIdRoute: MyOrdersIdRoute,
  OrderProductIdRoute: OrderProductIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ThanhToanOrderIdRoute: ThanhToanOrderIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  MyOrdersIndexRoute: MyOrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
